/**
 * client.ts — typed API client wrapping openapi-fetch.
 * DOC 3 Web App Shell: shared/api/client.ts
 *
 * STUB STRATEGY (C1): the base URL points to the API origin.
 * The client will be typed against schema.d.ts (from openapi-typescript) once
 * the FastAPI OpenAPI document exists (Track A Step A2).
 * `npm run types` must be re-run whenever the API schema changes.
 * Never hand-edit the generated parts of schema.d.ts.
 */

import createClient from "openapi-fetch";

// TODO(A2): replace with `import type { paths } from "./schema.d.ts"` once
// the FastAPI OpenAPI document exists and schema.d.ts is regenerated by
// openapi-typescript. For now we use an empty placeholder so CI is green.
type paths = Record<string, never>;

/**
 * Single shared API client instance.
 * All feature query hooks import from here — never from another feature.
 * Credentials (HttpOnly cookie) are included automatically.
 */
export const apiClient = createClient<paths>({
  baseUrl: "/api/v1",
  credentials: "same-origin",
  headers: {
    // CSRF mitigation: the API requires this custom header on mutating requests
    // (DOC 2 §2.2 security). It is sent on every request for simplicity.
    "X-Nakabandi-CSRF": "1",
  },
});
