/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingest/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Registry */
        post: operations["post_registry_api_v1_ingest_registry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Complaints */
        post: operations["post_complaints_api_v1_ingest_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/hops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Hops */
        post: operations["post_hops_api_v1_ingest_hops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/cashouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Cashout Observations */
        post: operations["post_cashout_observations_api_v1_ingest_cashouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/cashout-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Cashout Observations */
        post: operations["post_cashout_observations_api_v1_ingest_cashout_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Tick */
        post: operations["post_tick_api_v1_ingest_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_v1_geo_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_geo_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_v1_analytics_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeseries */
        get: operations["timeseries_api_v1_analytics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/live-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Metrics */
        get: operations["live_metrics_api_v1_analytics_live_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check */
        get: operations["check_api_v1_auth_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Users
         * @description Quick-login accounts for demos. 404 when NAKABANDI_DEMO_USERS_ENABLED is false: a
         *     deployment that is not a demo must not publish credentials (DOC 2 §2.8 T19).
         */
        get: operations["demo_users_api_v1_auth_demo_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit */
        get: operations["verify_audit_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description GET /api/v1/alerts — paginated; filtered by principal scope (LC-4 Page<AlertSummary>).
         *
         *     `view`: "queue" (default) is what the alert budget shows; "backlog" the deferred alerts that
         *     stay reachable; "all" both; "review" the officer's uncertainty-ordered feedback queue.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert
         * @description GET /api/v1/alerts/{id} — AlertDetail (LC-4); 403 outside the principal's scope.
         */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Alert
         * @description POST /api/v1/alerts/{id}/acknowledge — transitions to acknowledged.
         */
        post: operations["acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Action
         * @description 403 FORBIDDEN_PERMISSION (audited as denied), 409 INVALID_TRANSITION, 422 LIEN_INVALID.
         */
        post: operations["record_action_api_v1_alerts__alert_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Outcome
         * @description 201 for a new outcome, 200 for a repeat of the same (alert, result, location). 403 without
         *     MARK_OUTCOME or outside scope; 422 for an unknown result or a location not in the registry.
         */
        post: operations["mark_outcome_api_v1_alerts__alert_id__outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/bank/callbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bank Callback */
        post: operations["bank_callback_api_v1_integrations_bank_callbacks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outbox */
        get: operations["list_outbox_api_v1_outbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description GET /api/v1/stream — text/event-stream per LC-5.
         */
        get: operations["stream_api_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Metrics */
        get: operations["system_metrics_api_v1_system_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clusters
         * @description Known clusters = clusters that already have a bundled case (DOC 3 S1).
         */
        get: operations["list_clusters_api_v1_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cluster */
        get: operations["get_cluster_api_v1_clusters__cluster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/evidence-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Evidence Pack
         * @description Authorization (CREATE_EVIDENCE, and VIEW_ALERTS/scope on the underlying alert) happens
         *     inside the use case, since it needs the alert row to check scope.
         */
        post: operations["build_evidence_pack_api_v1_alerts__alert_id__evidence_pack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence-packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Pack */
        get: operations["get_evidence_pack_api_v1_evidence_packs__pack_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence-packs/{pack_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Evidence Pack */
        get: operations["download_evidence_pack_api_v1_evidence_packs__pack_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIn */
        AccountIn: {
            /** Account Ref */
            account_ref: string;
            /** Bank Id */
            bank_id: string;
            /** Home Location Id */
            home_location_id?: string | null;
        };
        /** AccountRefModel */
        AccountRefModel: {
            /** Masked Ref */
            masked_ref: string;
            /** Bank */
            bank: string;
            /** Complaint Count */
            complaint_count: number;
        };
        /** ActionInModel */
        ActionInModel: {
            type: components["schemas"]["ActionType"];
            /** Reason */
            reason?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** ActionModel */
        ActionModel: {
            /** Id */
            id: string;
            /** Alert Id */
            alert_id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Actor Role */
            actor_role: string;
            /** At */
            at: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Reason */
            reason?: string | null;
            /** Applied Amount Paise */
            applied_amount_paise?: number | null;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "acknowledge" | "request_hold" | "notify_station" | "dispatch" | "override";
        /** AlertDetailModel */
        AlertDetailModel: {
            /** Id */
            id: string;
            /** Cluster Ref */
            cluster_ref: string;
            /** Target */
            target: {
                [key: string]: unknown;
            };
            /** Severity */
            severity: string;
            /** Confidence */
            confidence: number;
            /** Status */
            status: string;
            /** Is Deferred */
            is_deferred: boolean;
            /** Is Probe */
            is_probe: boolean;
            /** Window Start */
            window_start: string;
            /** Window End */
            window_end: string;
            /** Expires At */
            expires_at: string;
            /** Ladder Level */
            ladder_level: string;
            /** Created At */
            created_at: string;
            /** Masked */
            masked: boolean;
            forecast: components["schemas"]["ForecastModel"] | null;
            /** Interception */
            interception: components["schemas"]["InterceptAssessmentModel"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEntryModel"][];
            /** Deliveries */
            deliveries: components["schemas"]["DeliveryModel"][];
            /** Actions */
            actions: components["schemas"]["ActionModel"][];
            /** Outcomes */
            outcomes: components["schemas"]["OutcomeView"][];
            /** Allowed Actions */
            allowed_actions: string[];
        };
        /** AlertSummaryModel */
        AlertSummaryModel: {
            /** Id */
            id: string;
            /** Cluster Ref */
            cluster_ref: string;
            /** Target */
            target: {
                [key: string]: unknown;
            };
            /** Severity */
            severity: string;
            /** Confidence */
            confidence: number;
            /** Status */
            status: string;
            /** Is Deferred */
            is_deferred: boolean;
            /** Is Probe */
            is_probe: boolean;
            /** Window Start */
            window_start: string;
            /** Window End */
            window_end: string;
            /** Expires At */
            expires_at: string;
            /** Ladder Level */
            ladder_level: string;
            /** Created At */
            created_at: string;
            /** Masked */
            masked: boolean;
        };
        /** AuditEntryResponse */
        AuditEntryResponse: {
            /** Seq */
            seq: number;
            /** At */
            at: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /** Reason */
            reason: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Hash */
            hash: string;
        };
        /** BankCallbackAck */
        BankCallbackAck: {
            /** Ack */
            ack: boolean;
            /** Applied */
            applied: boolean;
        };
        /** BankCallbackBody */
        BankCallbackBody: {
            /** Request Id */
            request_id: string;
            /** Status */
            status: string;
            /**
             * At Sim
             * Format: date-time
             */
            at_sim: string;
            /** Applied Amount Paise */
            applied_amount_paise?: number | null;
            /** Note */
            note?: string | null;
        };
        /** BestUnitModel */
        BestUnitModel: {
            /** Unit Id */
            unit_id: string;
            /** Unit Kind */
            unit_kind: string;
            /** Eta Min */
            eta_min: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** CaseModel */
        CaseModel: {
            /** Id */
            id: string;
            /** Cluster Ref */
            cluster_ref: string;
            /** Complaint Count */
            complaint_count: number;
            /** Victim Count */
            victim_count: number;
            /** Total Paise */
            total_paise: number;
            /** First Seen */
            first_seen: string;
            /** Last Seen */
            last_seen: string;
            /** Accounts */
            accounts: components["schemas"]["AccountRefModel"][];
            /** Top Locations */
            top_locations: components["schemas"]["LocationHitModel"][];
            /** Sub Communities */
            sub_communities: string[][];
            /** Brief Md */
            brief_md: string;
            /** Single Complaint */
            single_complaint: boolean;
            /** Built At */
            built_at: string | null;
        };
        /** CasePageModel */
        CasePageModel: {
            /** Items */
            items: components["schemas"]["CaseModel"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CashOutObsIn */
        CashOutObsIn: {
            /** Account Ref */
            account_ref: string;
            /** Location Id */
            location_id: string;
            channel: components["schemas"]["Channel"];
            /** Amount Paise */
            amount_paise: number;
            /**
             * Event At
             * Format: date-time
             */
            event_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Source
             * @enum {string}
             */
            source: "bank_report" | "police_report";
        };
        /** CashOutObservationBatch */
        CashOutObservationBatch: {
            /** Batch Id */
            batch_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Items */
            items: components["schemas"]["CashOutObsIn"][];
        };
        /**
         * Channel
         * @description The channel a cash-out (or attempted cash-out) happens through.
         * @enum {string}
         */
        Channel: "ATM" | "BRANCH" | "AGENT";
        /** ClusterEdgeModel */
        ClusterEdgeModel: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Amount Paise */
            amount_paise: number | null;
            /** Layer */
            layer: number;
            /** Event At */
            event_at: string;
        };
        /** ClusterModel */
        ClusterModel: {
            /** Cluster Ref */
            cluster_ref: string;
            /** Size */
            size: number;
            /** Status */
            status: string;
            /** Novelty */
            novelty: number;
            /** Nodes */
            nodes: components["schemas"]["ClusterNodeModel"][];
            /** Edges */
            edges: components["schemas"]["ClusterEdgeModel"][];
        };
        /** ClusterNodeModel */
        ClusterNodeModel: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Masked Ref */
            masked_ref: string;
            /** Bank */
            bank: string;
        };
        /** ComplaintBatch */
        ComplaintBatch: {
            /** Batch Id */
            batch_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Items */
            items: components["schemas"]["ComplaintIn"][];
        };
        /**
         * ComplaintCategory
         * @enum {string}
         */
        ComplaintCategory: "digital_arrest" | "investment_scam" | "upi_phishing" | "task_job_scam";
        /** ComplaintIn */
        ComplaintIn: {
            /** External Ref */
            external_ref: string;
            category: components["schemas"]["ComplaintCategory"];
            /** Amount Paise */
            amount_paise: number;
            /** Victim District Id */
            victim_district_id: string;
            /**
             * Credited At
             * Format: date-time
             */
            credited_at: string;
            /**
             * Reported Event At
             * Format: date-time
             */
            reported_event_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            layer1_account: components["schemas"]["AccountIn"];
        };
        /**
         * DeliveryModel
         * @description LC-4 AlertDetail.deliveries: { channel, status, attempts, sent_at?, rendered_body? }.
         */
        DeliveryModel: {
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Sent At */
            sent_at: string | null;
            /** Rendered Body */
            rendered_body: string | null;
        };
        /** DeliveryView */
        DeliveryView: {
            /** Id */
            id: string;
            /** Alert Id */
            alert_id: string;
            /** Action Id */
            action_id: string | null;
            /** Channel */
            channel: string;
            /** Provider */
            provider: string | null;
            /** Webhook Kind */
            webhook_kind: string | null;
            /** Recipient */
            recipient: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Next Attempt At */
            next_attempt_at: string;
            /** Created At */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Rendered Body */
            rendered_body: string;
        };
        /** DemoUserResponse */
        DemoUserResponse: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Role */
            role: string;
            /** Display Name */
            display_name: string;
        };
        /** EvidenceModel */
        EvidenceModel: {
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: string;
            };
            /** Text En */
            text_en: string;
        };
        /** EvidencePackModel */
        EvidencePackModel: {
            /** Id */
            id: string;
            /** Alert Id */
            alert_id: string;
            /** Case Id */
            case_id: string | null;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
            /** Created By Role */
            created_by_role: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Audit Head Hash */
            audit_head_hash: string;
            /** Download Url */
            download_url: string;
        };
        /**
         * ForecastModel
         * @description LC-4 Forecast.
         */
        ForecastModel: {
            /** Id */
            id: string;
            /** Complaint Id */
            complaint_id: string;
            /** Cluster Id */
            cluster_id: string | null;
            /** Generated At */
            generated_at: string;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Levels */
            levels: {
                [key: string]: components["schemas"]["LevelForecastModel"];
            };
            timing: components["schemas"]["TimingForecastModel"];
            /** Confidence */
            confidence: number;
            /** Novelty */
            novelty: number;
            /** Stale */
            stale: boolean;
            /** Evidence */
            evidence: components["schemas"]["EvidenceModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatCellView */
        HeatCellView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Value */
            value: number;
            /** Alert Count */
            alert_count: number;
        };
        /**
         * HeatmapResponse
         * @description LC-4 HeatmapResponse.
         */
        HeatmapResponse: {
            /** Layer */
            layer: string;
            /** Level */
            level: string;
            /** Generated At */
            generated_at: string;
            /** Version */
            version: number;
            /** Cells */
            cells: components["schemas"]["HeatCellView"][];
            /** Suppressed Count */
            suppressed_count: number;
            legend: components["schemas"]["LegendView"];
        };
        /** HopBatch */
        HopBatch: {
            /** Batch Id */
            batch_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Items */
            items: components["schemas"]["HopIn"][];
        };
        /** HopIn */
        HopIn: {
            /** Complaint External Ref */
            complaint_external_ref: string;
            from_account: components["schemas"]["AccountIn"];
            to_account: components["schemas"]["AccountIn"];
            /** Amount Paise */
            amount_paise: number;
            /** Layer */
            layer: number;
            /**
             * Event At
             * Format: date-time
             */
            event_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /**
         * IngestResponse
         * @description The `Response (all)` shape in LC-1: shared by every ingestion endpoint.
         */
        IngestResponse: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: components["schemas"]["RejectedItem"][];
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
        };
        /**
         * InterceptAssessmentModel
         * @description LC-4 InterceptAssessment.
         */
        InterceptAssessmentModel: {
            /** Id */
            id: string;
            /** Forecast Id */
            forecast_id: string;
            /** Target */
            target: {
                [key: string]: string;
            };
            /** Channel */
            channel: string;
            /** Window Min */
            window_min: number;
            best_unit: components["schemas"]["BestUnitModel"] | null;
            /** Interception Probability */
            interception_probability: number;
            /** Verdict */
            verdict: string;
            /** Ladder Level */
            ladder_level: string;
            /** Reason Code */
            reason_code: string;
            /** Reason Params */
            reason_params: {
                [key: string]: string;
            };
            proportionality: components["schemas"]["ProportionalityModel"] | null;
        };
        /** LatencyView */
        LatencyView: {
            /** Count */
            count: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Max Ms */
            max_ms: number;
        };
        /**
         * Layer
         * @enum {string}
         */
        Layer: "live" | "potential";
        /** LegendView */
        LegendView: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Unit */
            unit: string;
            /** Note */
            note: string;
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "district" | "cell" | "location";
        /** LevelForecastModel */
        LevelForecastModel: {
            /** Resolution */
            resolution: string;
            /** Abstained */
            abstained: boolean;
            /** Confidence */
            confidence: number;
            /** Items */
            items: components["schemas"]["RankedItemModel"][];
        };
        /** LiveMetricsResponse */
        LiveMetricsResponse: {
            /** Generated At */
            generated_at: string;
            /** Version */
            version: number;
            /** Window Hours */
            window_hours: number;
            /** Alert Count */
            alert_count: number;
            /** Expected Mass */
            expected_mass: number;
            /** Active Locations */
            active_locations: number;
        };
        /** LocationHitModel */
        LocationHitModel: {
            /** Location Id */
            location_id: string;
            /** Count */
            count: number;
            /** Last At */
            last_at: string;
        };
        /**
         * LocationKind
         * @description The kind of a registry location. Same members as Channel (LC-2), kept as a
         *     separate enum because a location's kind and a transaction's channel are distinct
         *     concepts that happen to share a value set.
         * @enum {string}
         */
        LocationKind: "ATM" | "BRANCH" | "AGENT";
        /** LocationPage */
        LocationPage: {
            /** Items */
            items: components["schemas"]["LocationView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** LocationView */
        LocationView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Bank Id */
            bank_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** District Id */
            district_id: string;
            /** Cell Id */
            cell_id: string;
            /** Display Name */
            display_name: string;
            /** Area Type */
            area_type: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Expires At */
            expires_at: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Permissions */
            permissions: string[];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Generated At */
            generated_at: string;
            /** Uptime S */
            uptime_s: number;
            /** Events Per Second */
            events_per_second: number;
            /** Complaints Per Second */
            complaints_per_second: number;
            /** Stages */
            stages: {
                [key: string]: components["schemas"]["LatencyView"];
            };
            http: components["schemas"]["LatencyView"];
            /** Outbox */
            outbox: {
                [key: string]: number;
            };
            /** Delivery Failures */
            delivery_failures: number;
            /** Streams */
            streams: {
                [key: string]: number;
            };
        };
        /** OutboxPage */
        OutboxPage: {
            /** Items */
            items: components["schemas"]["DeliveryView"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Dead Count */
            dead_count: number;
        };
        /** OutcomeIn */
        OutcomeIn: {
            /** Result */
            result: string;
            /** Location Id */
            location_id?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * OutcomeView
         * @description LC-4 Outcome: { id, alert_id, result, source: officer|reconciled, at }.
         */
        OutcomeView: {
            /** Id */
            id: string;
            /** Alert Id */
            alert_id: string;
            /** Result */
            result: string;
            /** Source */
            source: string;
            /** At */
            at: string;
        };
        /** PageModel */
        PageModel: {
            /** Items */
            items: components["schemas"]["AlertSummaryModel"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ProportionalityModel */
        ProportionalityModel: {
            /** Disputed Paise */
            disputed_paise: number;
            /** Proposed Paise */
            proposed_paise: number;
            /** Ratio */
            ratio: number;
            /** Expires At */
            expires_at: string;
            /** Review At */
            review_at: string;
            /** Magistrate Report Reminder */
            magistrate_report_reminder: boolean;
            /** Complaint Ref */
            complaint_ref: string;
        };
        /** RankedItemModel */
        RankedItemModel: {
            /** Id */
            id: string;
            /** Prob */
            prob: number;
            /** Rank */
            rank: number;
        };
        /** RegionView */
        RegionView: {
            /** Id */
            id: string;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Geojson Ref */
            geojson_ref: string | null;
        };
        /** RegistryLocation */
        RegistryLocation: {
            /** Id */
            id: string;
            kind: components["schemas"]["LocationKind"];
            /** Bank Id */
            bank_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** District Id */
            district_id: string;
            /** Cell Id */
            cell_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "osm" | "synthetic";
            /** Display Name */
            display_name: string;
            /**
             * Area Type
             * @enum {string}
             */
            area_type: "urban" | "semi_urban" | "rural";
            /** Activity Index */
            activity_index: number;
        };
        /** RegistryUnit */
        RegistryUnit: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "cyber_cell" | "station" | "patrol";
            /** District Id */
            district_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Status */
            status: string;
        };
        /** RegistryUpdate */
        RegistryUpdate: {
            /** Version */
            version: string;
            /** Banks */
            banks: {
                [key: string]: unknown;
            }[];
            /** Regions */
            regions: {
                [key: string]: unknown;
            }[];
            /** Cells */
            cells: {
                [key: string]: unknown;
            }[];
            /** Locations */
            locations: components["schemas"]["RegistryLocation"][];
            /** Units */
            units: components["schemas"]["RegistryUnit"][];
        };
        /** RejectedItem */
        RejectedItem: {
            /** Index */
            index: number;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "i4c_analyst" | "state_investigator" | "district_officer" | "bank_nodal" | "demo_operator" | "admin";
        /** Tick */
        Tick: {
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
        };
        /** TimePointView */
        TimePointView: {
            /** Hour */
            hour: string;
            /** Value */
            value: number;
            /** Alert Count */
            alert_count: number;
        };
        /** TimelineEntryModel */
        TimelineEntryModel: {
            /** At */
            at: string;
            /** Kind */
            kind: string;
            /** Actor Id */
            actor_id: string | null;
            /** Text Code */
            text_code: string;
            /** Text Params */
            text_params: {
                [key: string]: unknown;
            };
        };
        /** TimeseriesResponse */
        TimeseriesResponse: {
            /** Layer */
            layer: string;
            /** From */
            from_: string;
            /** To */
            to: string;
            /** Version */
            version: number;
            /** Points */
            points: components["schemas"]["TimePointView"][];
        };
        /** TimingForecastModel */
        TimingForecastModel: {
            /** Weights */
            weights: number[];
            /** Medians Min */
            medians_min: number[];
            /** Sigmas */
            sigmas: number[];
            /** Elapsed Min */
            elapsed_min: number;
            /** Residual Mass */
            residual_mass: number;
            /** P30 */
            p30: number;
            /** P60 */
            p60: number;
            /** P120 */
            p120: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Ok */
            ok: boolean;
            /** First Bad Seq */
            first_bad_seq: number | null;
            /** Head Hash */
            head_hash: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_registry_api_v1_ingest_registry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_complaints_api_v1_ingest_complaints_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_hops_api_v1_ingest_hops_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HopBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cashout_observations_api_v1_ingest_cashouts_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashOutObservationBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cashout_observations_api_v1_ingest_cashout_observations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashOutObservationBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_tick_api_v1_ingest_tick_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                "x-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tick"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_v1_geo_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionView"][];
                };
            };
        };
    };
    list_locations_api_v1_geo_locations_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                kind?: components["schemas"]["LocationKind"] | null;
                bank_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_v1_analytics_heatmap_get: {
        parameters: {
            query?: {
                from_?: string | null;
                layer?: components["schemas"]["Layer"];
                level?: components["schemas"]["Level"];
                to?: string | null;
                state?: string | null;
                district?: string | null;
                category?: string | null;
                amount_band?: number | null;
                min_confidence?: number | null;
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_api_v1_analytics_timeseries_get: {
        parameters: {
            query?: {
                from_?: string | null;
                layer?: components["schemas"]["Layer"];
                to?: string | null;
                state?: string | null;
                district?: string | null;
                category?: string | null;
                amount_band?: number | null;
                min_confidence?: number | null;
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_metrics_api_v1_analytics_live_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMetricsResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    check_api_v1_auth_check_get: {
        parameters: {
            query: {
                role: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_users_api_v1_auth_demo_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoUserResponse"][];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryResponse"][];
                };
            };
        };
    };
    verify_audit_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                status?: string | null;
                view?: "queue" | "backlog" | "all" | "review";
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_action_api_v1_alerts__alert_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionInModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_outcome_api_v1_alerts__alert_id__outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bank_callback_api_v1_integrations_bank_callbacks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nakabandi-service-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankCallbackBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankCallbackAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outbox_api_v1_outbox_get: {
        parameters: {
            query?: {
                status?: string | null;
                channel?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    system_metrics_api_v1_system_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    list_clusters_api_v1_clusters_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePageModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cluster_api_v1_clusters__cluster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePageModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_evidence_pack_api_v1_alerts__alert_id__evidence_pack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePackModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_pack_api_v1_evidence_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePackModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_evidence_pack_api_v1_evidence_packs__pack_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
